# Generated by Django 4.2 on 2023-04-15 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
